version: '2'
linters:
  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - grouper
    - iface
    - importas
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - tagalign
    - testpackage
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
  settings:
    gocritic:
      disabled-checks:
        - commentedOutCode
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    misspell:
      locale: US
    nolintlint:
      require-specific: true
    sloglint:
      msg-style: lowercased
      key-naming-case: snake
    varnamelen:
      max-distance: 20
